import express from 'express';
import Database from 'better-sqlite3';
import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync } from 'node:fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const dataDir = path.join(root, 'data');
if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });
const db = new Database(process.env.LINKTRACER_DB || path.join(dataDir, 'linktracer.db'));
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS links (id TEXT PRIMARY KEY,canonical_url TEXT NOT NULL UNIQUE,url TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',descriptions TEXT NOT NULL DEFAULT '[]',tags TEXT NOT NULL DEFAULT '[]',source_context TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,revision INTEGER NOT NULL DEFAULT 1);CREATE INDEX IF NOT EXISTS idx_links_updated ON links(updated_at);CREATE TABLE IF NOT EXISTS change_log (seq INTEGER PRIMARY KEY AUTOINCREMENT,canonical_url TEXT NOT NULL,revision INTEGER NOT NULL,changed_at INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS idx_change_log_seq ON change_log(seq);CREATE TABLE IF NOT EXISTS collections (id TEXT PRIMARY KEY,payload TEXT NOT NULL,updated_at INTEGER NOT NULL,revision INTEGER NOT NULL DEFAULT 1,deleted INTEGER NOT NULL DEFAULT 0);CREATE INDEX IF NOT EXISTS idx_collections_updated ON collections(updated_at);CREATE TABLE IF NOT EXISTS collection_change_log (seq INTEGER PRIMARY KEY AUTOINCREMENT,collection_id TEXT NOT NULL,revision INTEGER NOT NULL,changed_at INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS idx_collection_change_log_seq ON collection_change_log(seq);CREATE TABLE IF NOT EXISTS sync_operations (change_id TEXT PRIMARY KEY,accepted_at INTEGER NOT NULL);`);
const app=express();app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(root,'public')));
function canonicalize(raw){const u=new URL(raw.trim());if(!['http:','https:'].includes(u.protocol))throw Error('Only http and https links are supported');u.hash='';['utm_source','utm_medium','utm_campaign','utm_term','utm_content','gclid','fbclid'].forEach(k=>u.searchParams.delete(k));return u.toString().replace(/\/$/,'')}
function autoTags(text){const stop=new Set('the and for with from this that your have into about after before when what which where while link https http www com org net'.split(' '));const words=text.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(w=>w.length>=4&&!stop.has(w));const counts=new Map();for(const w of words)counts.set(w,(counts.get(w)||0)+1);return[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,8).map(([w])=>w)}
function classify(url,title='',text=''){const u=new URL(url),h=`${u.hostname} ${u.pathname} ${title} ${text.slice(0,4000)}`.toLowerCase();const rules=[['video',/youtube|youtu\.be|vimeo|video|watch/],['code',/github|gitlab|bitbucket|stackoverflow|\.md\b|repository|source code|api reference/],['documentation',/docs\.|documentation|reference|developer|\/docs(?:\/|$)|\/api(?:\/|$)/],['article',/article|blog|post|medium\.com|substack|news|journal|read|analysis/],['paper',/arxiv|researchgate|doi\.org|paper|abstract|proceedings|publication/],['social',/x\.com|twitter|linkedin|reddit|threads|facebook/],['product',/product|pricing|features|shop|store|marketplace/]];for(const[x,p]of rules)if(p.test(h))return x;return'webpage'}
function htmlToText(html){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()}
function extractMeta(html,key){const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),patterns=[new RegExp(`<meta[^>]+(?:name|property)=["']${escaped}["'][^>]*content=["']([^"']*)["'][^>]*>`,'i'),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]*(?:name|property)=["']${escaped}["'][^>]*>`,'i')];for(const re of patterns){const value=html.match(re)?.[1]?.trim();if(value)return value}return''}
async function fetchUrl(url,method='GET'){return fetch(url,{method,redirect:'follow',signal:AbortSignal.timeout(7000),headers:{'user-agent':'Linktracer/1.1'}})}
async function enrich(url){try{const response=await fetchUrl(url),html=(await response.text()).slice(0,2000000),title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()||'',description=extractMeta(html,'description')||extractMeta(html,'og:description'),site=new URL(url).hostname.replace(/^www\./,''),text=htmlToText(html).slice(0,12000);return{title,description,site,status:response.status,finalUrl:response.url,responseTimeMs:null,favicon:`${new URL(url).origin}/favicon.ico`,excerpt:text,contentType:classify(url,title,`${description} ${text}`)}}catch{return{title:'',description:'',site:new URL(url).hostname.replace(/^www\./,''),status:0,finalUrl:url,responseTimeMs:null,favicon:'',excerpt:'',contentType:classify(url)}}}
async function checkHealth(url){const started=Date.now();try{let response=await fetchUrl(url,'HEAD');if(response.status===405||response.status===501)response=await fetchUrl(url,'GET');return{status:response.status,finalUrl:response.url,responseTimeMs:Date.now()-started,checkedAt:Date.now(),healthy:response.ok}}catch(error){return{status:0,finalUrl:url,responseTimeMs:Date.now()-started,checkedAt:Date.now(),healthy:false,error:error.message||'request failed'}}}
async function checkPreservation(url){const response=await fetch(`https://archive.org/wayback/available?url=${encodeURIComponent(url)}`,{redirect:'follow',signal:AbortSignal.timeout(7000),headers:{'user-agent':'Linktracer/1.1'}});if(!response.ok)throw Error(`Archive availability returned ${response.status}`);const body=await response.json(),closest=body?.archived_snapshots?.closest;return{archived:Boolean(closest?.available),timestamp:closest?.timestamp||null,archiveUrl:closest?.url||null,checkedAt:Date.now(),source:'internet-archive-wayback'}}
function parseDescriptions(v){try{return Array.isArray(v)?v:JSON.parse(v||'[]')}catch{return[]}}function parseTags(v){try{return[...new Set((Array.isArray(v)?v:JSON.parse(v||'[]')).map(String).map(s=>s.trim().toLowerCase()).filter(Boolean))]}catch{return[]}}function mergedDescriptions(items){const seen=new Set();return items.filter(x=>x?.text?.trim()).filter(x=>{const k=x.text.trim().toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).map(x=>({text:x.text.trim(),deviceId:x.deviceId||'unknown',updatedAt:Number(x.updatedAt||0)}))}function mergedDescription(items){return mergedDescriptions(items).map(x=>x.text).join('\n\n')}function rowToLink(row){const descriptions=parseDescriptions(row.descriptions);return{id:row.id,url:row.url,canonicalUrl:row.canonical_url,title:row.title,description:mergedDescription(descriptions),descriptions,tags:parseTags(row.tags),sourceContext:JSON.parse(row.source_context||'{}'),createdAt:row.created_at,updatedAt:row.updated_at,revision:row.revision}}
const get=db.prepare('SELECT * FROM links WHERE canonical_url = ?'),insert=db.prepare('INSERT INTO links (id,canonical_url,url,title,descriptions,tags,source_context,created_at,updated_at,revision) VALUES (?,?,?,?,?,?,?,?,?,?)'),update=db.prepare('UPDATE links SET url=?,title=?,descriptions=?,tags=?,source_context=?,updated_at=?,revision=revision+1 WHERE canonical_url=?'),logChange=db.prepare('INSERT INTO change_log (canonical_url,revision,changed_at) VALUES (?,?,?)'),seenOperation=db.prepare('SELECT 1 FROM sync_operations WHERE change_id = ?'),recordOperation=db.prepare('INSERT INTO sync_operations (change_id,accepted_at) VALUES (?,?)');
function mergeLink(input,existing,now){const canonicalUrl=canonicalize(input.url||input.canonicalUrl),descriptions=existing?parseDescriptions(existing.descriptions):[],incoming=Array.isArray(input.descriptions)&&input.descriptions.length?input.descriptions:(input.description?[{text:input.description,deviceId:input.deviceId||'unknown',updatedAt:now}]:[]),merged=mergedDescriptions([...descriptions,...incoming]),tags=[...new Set([...(existing?parseTags(existing.tags):[]),...parseTags(input.tags||[])])],context={...(existing?JSON.parse(existing.source_context||'{}'):{}),...(input.sourceContext||{})},title=input.title?.trim()||existing?.title||'',url=input.url?.trim()||existing?.url||canonicalUrl;if(!existing){const id=input.id||randomUUID();insert.run(id,canonicalUrl,url,title,JSON.stringify(merged),JSON.stringify(tags),JSON.stringify(context),now,now,1);logChange.run(canonicalUrl,1,now);return rowToLink(get.get(canonicalUrl))}update.run(url,title,JSON.stringify(merged),JSON.stringify(tags),JSON.stringify(context),now,canonicalUrl);const updated=get.get(canonicalUrl);logChange.run(canonicalUrl,updated.revision,now);return rowToLink(updated)}
function deleteLink(canonicalUrl,now){const existing=get.get(canonicalUrl);if(!existing)return false;db.prepare('DELETE FROM links WHERE canonical_url=?').run(canonicalUrl);logChange.run(canonicalUrl,(existing.revision||1)+1,now);return true}
function mergeChecklist(a,b){const map=new Map((Array.isArray(a)?a:[]).map(x=>[x.id,x]));for(const item of Array.isArray(b)?b:[]){const old=map.get(item.id);map.set(item.id,old?{...old,...item,done:Boolean(old.done||item.done)}:item)}return[...map.values()]}
function mergeCollection(input,existing,now){const incoming=input.payload&&typeof input.payload==='object'?input.payload:input,current=existing&&!existing.deleted?JSON.parse(existing.payload||'{}'):{};const merged={...current,...incoming,updatedAt:Math.max(Number(current.updatedAt||0),Number(incoming.updatedAt||0),now)};if(Array.isArray(current.checklist)||Array.isArray(incoming.checklist))merged.checklist=mergeChecklist(current.checklist,incoming.checklist);if(Array.isArray(current.linkedTags)||Array.isArray(incoming.linkedTags))merged.linkedTags=[...new Set([...(current.linkedTags||[]),...(incoming.linkedTags||[])])];const revision=(existing?.revision||0)+1;db.prepare('INSERT INTO collections(id,payload,updated_at,revision,deleted) VALUES(?,?,?,?,0) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at,revision=excluded.revision,deleted=0').run(String(incoming.id),JSON.stringify(merged),merged.updatedAt,revision);db.prepare('INSERT INTO collection_change_log(collection_id,revision,changed_at) VALUES(?,?,?)').run(String(incoming.id),revision,now);return merged}
function deleteCollection(id,now){const existing=db.prepare('SELECT * FROM collections WHERE id=?').get(id),revision=(existing?.revision||0)+1;db.prepare('INSERT INTO collections(id,payload,updated_at,revision,deleted) VALUES(?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET updated_at=excluded.updated_at,revision=excluded.revision,deleted=1').run(id,'{}',now,revision);db.prepare('INSERT INTO collection_change_log(collection_id,revision,changed_at) VALUES(?,?,?)').run(String(id),revision,now)}
app.get('/api/links',(req,res)=>{const cursor=Number(req.query.cursor||0),safeCursor=Number.isFinite(cursor)&&cursor>=0?cursor:0,changes=db.prepare('SELECT seq,canonical_url FROM change_log WHERE seq>? ORDER BY seq ASC LIMIT 500').all(safeCursor),uniqueUrls=[...new Set(changes.map(x=>x.canonical_url))],rows=uniqueUrls.map(url=>get.get(url)).filter(Boolean),nextCursor=changes.length?changes[changes.length-1].seq:safeCursor;res.json({links:rows.map(rowToLink),serverTime:Date.now(),cursor:nextCursor,hasMore:changes.length===500})});
app.get('/api/collections',(req,res)=>{const cursor=Number(req.query.cursor||0),safeCursor=Number.isFinite(cursor)&&cursor>=0?cursor:0,changes=db.prepare('SELECT seq,collection_id FROM collection_change_log WHERE seq>? ORDER BY seq ASC LIMIT 500').all(safeCursor),ids=[...new Set(changes.map(x=>x.collection_id))],rows=ids.map(id=>db.prepare('SELECT * FROM collections WHERE id=?').get(id)).filter(Boolean),nextCursor=changes.length?changes[changes.length-1].seq:safeCursor;res.json({collections:rows.map(r=>({...JSON.parse(r.payload||'{}'),id:r.id,revision:r.revision,updatedAt:r.updated_at,deleted:Boolean(r.deleted)})),serverTime:Date.now(),cursor:nextCursor,hasMore:changes.length===500})});
app.get('/api/search',(req,res)=>{const q=String(req.query.q||'').trim().toLowerCase(),rows=db.prepare('SELECT * FROM links ORDER BY updated_at DESC').all().map(rowToLink);if(!q)return res.json({links:rows.slice(0,100),count:rows.length});const terms=q.split(/\s+/).filter(Boolean),results=rows.filter(link=>{const hay=JSON.stringify(link).toLowerCase();return terms.every(term=>hay.includes(term))}).slice(0,100);res.json({links:results,count:results.length})});
app.get('/api/preservation',async(req,res)=>{try{const url=canonicalize(req.query.url||'');res.json({url,...(await checkPreservation(url))})}catch(error){res.status(502).json({error:error.message||'Preservation lookup failed'})}});
const syncBatch=db.transaction(changes=>{const merged=[],acceptedChangeIds=[],rejectedChanges=[];for(const change of changes){const changeId=String(change?.changeId||'');try{if(!changeId)throw Error('missing changeId');if(seenOperation.get(changeId)){acceptedChangeIds.push(changeId);continue}if(change.entityType==='collection'){const id=String(change.collection?.id||change.id||'');if(!id)throw Error('missing collection id');if(change.deleted){deleteCollection(id,Date.now());merged.push({id,deleted:true})}else{const existing=db.prepare('SELECT * FROM collections WHERE id=?').get(id);merged.push(mergeCollection(change.collection||change,existing,Date.now()))}recordOperation.run(changeId,Date.now());acceptedChangeIds.push(changeId);continue}if(change.entityType==='link'){const canonical=canonicalize(change.url||change.canonicalUrl||'');if(change.deleted){deleteLink(canonical,Date.now());merged.push({canonicalUrl:canonical,deleted:true})}else merged.push(mergeLink(change,get.get(canonical),Date.now()));recordOperation.run(changeId,Date.now());acceptedChangeIds.push(changeId);continue}const canonical=canonicalize(change.url||change.canonicalUrl||'');merged.push(mergeLink(change,get.get(canonical),Date.now()));recordOperation.run(changeId,Date.now());acceptedChangeIds.push(changeId)}catch(error){rejectedChanges.push({changeId,error:error.message||'invalid change'})}}return{merged,acceptedChangeIds,rejectedChanges}});
app.post('/api/sync',(req,res)=>{const changes=Array.isArray(req.body?.changes)?req.body.changes:[],result=syncBatch(changes);res.json({...result,links:result.merged.filter(x=>x?.url&&!x?.deleted),collections:result.merged.filter(x=>x?.id&&!x?.url),serverTime:Date.now()})});
app.post('/api/enrich',async(req,res)=>{try{const url=canonicalize(req.body?.url||''),context=await enrich(url);res.json({url,...context,tags:autoTags(`${url} ${context.title} ${context.description} ${context.excerpt}`),enrichedAt:Date.now()})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/link-health',async(req,res)=>{try{const url=canonicalize(req.body?.url||'');res.json({url,...(await checkHealth(url))})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/health',(_req,res)=>res.json({ok:true,time:Date.now()}));app.get('*splat',(_req,res)=>res.sendFile(path.join(root,'public','index.html')));
const port=Number(process.env.PORT||8787);app.listen(port,'0.0.0.0',()=>console.log(`Linktracer running at http://localhost:${port}`));
